[[permission]]
identifier = "allow-scan"
description = "Izinkan frontend memanggil fungsi scan_music_folder, read_lrc_file, dan start_monitoring"
commands.allow = [
    "scan_music_folder", 
    "read_lrc_file", 
    "start_monitoring"
]

# --- TAMBAHKAN BAGIAN INI ---
[[permission]]
identifier = "allow-metadata"
description = "Izinkan frontend memanggil fungsi fetch data artis dan download image"
commands.allow = [
    "fetch_external_artist_data",
    "download_artist_image"
]
# ----------------------------

[[permission]]
identifier = "allow-audio-read"
description = "Allows reading audio files and covers from any location"
[[permission.scope.allow]]
path = "$APPLOCALDATA/covers/*"
[[permission.scope.allow]]
path = "**" # IZINKAN AKSES SEMUA PATH (UNIVERSAL)

[[set]]
identifier = "app-full-access"
description = "Full access for the application commands and assets"
permissions = [
    "allow-scan", 
    "allow-audio-read",
    "allow-metadata"  # <-- MASUKKAN IDENTIFIER BARU KE SINI
]