[[permission]]
identifier = "allow-scan"
description = "Izinkan frontend memanggil fungsi scan_music_folder"
commands.allow = ["scan_music_folder"]

[[permission]]
identifier = "allow-covers-read"
description = "Allows reading album cover files from local data"
[[permission.scope.allow]]
path = "$APPLOCALDATA/covers/*"

[[set]]
identifier = "app-full-access"
description = "Full access for the application commands and assets"
permissions = ["allow-scan", "allow-covers-read"]