[[permission]]
identifier = "allow-scan"
description = "Izinkan frontend memanggil fungsi scan_music_folder, read_lrc_file, dan start_monitoring"
commands.allow = [
    "scan_music_folder", 
    "read_lrc_file", 
    "start_monitoring"
]

[[permission]]
identifier = "allow-audio-read"
description = "Allows reading audio files and covers from any location"
[[permission.scope.allow]]
path = "$APPLOCALDATA/covers/*"
[[permission.scope.allow]]
path = "**" # IZINKAN AKSES SEMUA PATH (UNIVERSAL)

[[set]]
identifier = "app-full-access"
description = "Full access for the application commands and assets"
permissions = ["allow-scan", "allow-audio-read"]